name: OpenQuake on Ubuntu demo

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  openquake-on-ubuntu-demo:
    runs-on: ubuntu-20.04
    env:
      TIME_RUN: /usr/bin/time -v stdbuf -oL eatmydata
    if: "!contains(github.event.head_commit.message, '[ci skip]') && !contains(github.event.head_commit.message, '[skip ci]')"

    steps:
      - name: Checkout self
        uses: actions/checkout@v2
        with:
          path: main

      - name: Checkout secret OpenQuake-GitHub-Actions-demo repo
        uses: actions/checkout@v2
        with:
          path: private
          repository: OpenDRR/OpenQuake-GitHub-Actions-demo
          token: ${{ secrets.MY_PAT }}

      - name: Cache OpenQuake
        uses: actions/cache@v2
        id: cache
        with:
          path: ~/openquake
          key: ${{ runner.os }}-OpenQuake

      - name: Exploration
        run: |
          set -x
          pwd
          ls -l
          df -h
          whoami
          free -h
          cat /etc/os-release

      - name: Install OpenQuake
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          set -x
          curl https://raw.githubusercontent.com/gem/oq-engine/master/install.py -O
          python3 install.py user

      - name: Install eatmydata and GNU time
        run: |
          sudo stdbuf -oL apt-get update
          sudo stdbuf -oL apt-get install -y eatmydata time

      - name: Check size of OpenQuake installation
        run: |
          set -x
          pwd
          du -csh *
          du -csh ~/*

      - name: "OpenQuake: Run AreaSourceClassicalPSHA demo"
        run: |
          source ~/openquake/bin/activate
          $TIME_RUN oq engine --run ~/openquake/demos/hazard/AreaSourceClassicalPSHA/job.ini

      - name: pip3 install tqdm (for weightHAZ.py)
        run: |
          source ~/openquake/bin/activate
          $TIME_RUN pip3 install tqdm

      - name: "OpenQuake: Run Hazard calculation provided by Tiegan"
        env:
          JOBDIR: private/thobbs/scenario-catalogue/deterministic/initializations
          # OUTDIR is hardcoded as "outputs" in weightHAZ.py.  Don't change!
          OUTDIR: outputs
          AVGHAZLOC: private/scenario-catalogue/scripts/weightHAZ.py
          NAME: IDM5p7_CR2022Aftershock
        run: |
          source ~/openquake/bin/activate
          cp -av private/CanadaSHM6/OpenQuake_model_files/gmms/gsim/CanadaSHM6_* ~/openquake/lib/python3.8/site-packages/openquake/hazardlib/gsim/
          # Based on OpenDRR/scenario-catalogue/scripts/run_OQStandard.sh
          mkdir -p temp
          mkdir -p "$OUTDIR"
          echo "Outputs will be placed in $OUTDIR"
          $TIME_RUN oq engine --run $JOBDIR/s_Hazard_${NAME}.ini 2>&1 | tee $OUTDIR/s_Hazard_${NAME}.log
          $TIME_RUN oq export gmf_data -1 -e csv -d temp
          CALCID=`basename temp/*gmf* .csv | awk -F'_' '{print $NF}'`
          $TIME_RUN python3 $AVGHAZLOC $NAME $CALCID
          SMSFILE="$OUTDIR/s_sitemesh_${NAME}_${CALCID}.csv"
          mv temp/*sitemesh* ${SMSFILE}
          rm -v temp/sigma_epsilon_* temp/*gmf*.csv

      - name: Commit and push output files
        run: |
          mkdir -p main/outputs-from-ubuntu
          cp -av outputs/* main/outputs-from-ubuntu/
          cd main
          git config user.name github-actions
          git config user.email github-actions@github.com
          git pull
          git add .
          git commit -m "Save OpenQuake Hazard calculation output (Ubuntu)"
          git push
